# Generated by Django 2.2.6 on 2021-03-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amount',
            name='diposite_slip',
            field=models.ImageField(blank=True, default='diposite.jpg', null=True, upload_to=''),
        ),
    ]
