# Generated by Django 3.2 on 2021-04-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210418_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amount',
            name='diposite_slip',
            field=models.ImageField(blank=True, null=True, upload_to='images/amounts/'),
        ),
    ]
