# Generated by Django 2.2.6 on 2021-04-25 04:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_slider_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='aboutus',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
