# Generated by Django 2.2.6 on 2021-04-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_vision_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termsconditions',
            name='point',
        ),
        migrations.AddField(
            model_name='gallery',
            name='descriptions',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='publish_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
