# Generated by Django 2.2.6 on 2021-04-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_admin_panel',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=200),
        ),
    ]
