# Generated by Django 2.2.6 on 2020-12-31 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nid',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='occupation',
            field=models.CharField(blank=True, choices=[('', ''), ('Govt.', 'Govt.'), ('Semi Govt.', 'Semi Govt.'), ('Service', 'Service'), ('Business', 'Business'), ('Student', 'Student'), ('House Wife', 'House Wife')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='religion',
            field=models.CharField(blank=True, choices=[('Islam', 'Islam'), ('Hindu', 'Hindu')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Left', 'Left')], default='', max_length=200),
        ),
    ]
